# source: generated by Claude.ai
# run in rails bash shell with:
#       rails test test/models/user_test.rb

require "test_helper"

class UserTest < ActiveSupport::TestCase
  test "valid user" do
    user = User.new(username: "testuser", password: "password123")
    assert user.valid?
  end
  
  test "invalid without username" do
    user = User.new(password: "password123")
    assert_not user.valid?
    assert_includes user.errors[:username], "can't be blank"
  end
  
  test "invalid with short username" do
    user = User.new(username: "ab", password: "password123")
    assert_not user.valid?
  end
  
  test "invalid without password" do
    user = User.new(username: "testuser")
    assert_not user.valid?
  end
  
  test "invalid with short password" do
    user = User.new(username: "testuser", password: "12345")
    assert_not user.valid?
  end
  
  test "username must be unique" do
    User.create(username: "testuser", password: "password123")
    duplicate = User.new(username: "testuser", password: "password123")
    assert_not duplicate.valid?
  end
  
  test "username is case insensitive" do
    User.create(username: "TestUser", password: "password123")
    duplicate = User.new(username: "testuser", password: "password123")
    assert_not duplicate.valid?
  end
  
  test "password authentication" do
    user = User.create(username: "testuser", password: "password123")
    assert user.authenticate("password123")
    assert_not user.authenticate("wrongpassword")
  end
  
  test "expert? returns true when user has expert profile" do
    user = User.create(username: "expert", password: "password123")
    # We'll create the ExpertProfile model later
    # user.create_expert_profile(bio: "I'm an expert")
    # assert user.expert?
  end
end